<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-TF7AAOL" failures="1" tests="1" name="Test(failed)" time="13.431" errors="0" timestamp="2025-10-16T18:55:02 IST">
  <testcase classname="test.Login" name="verifyLoginWithValidCredentials" time="2.238">
    <failure type="java.lang.AssertionError" message="expected [My Account1] but found [My Account]">
      <![CDATA[java.lang.AssertionError: expected [My Account1] but found [My Account]
at test.Login.verifyLoginWithValidCredentials(Login.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="test.Login" name="verifyLoginwithInvalidEmailAndValidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginwithInvalidEmailAndValidPassword -->
  <testcase classname="test.Login" name="verifyLoginwithValidEmailAndInvalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginwithValidEmailAndInvalidPassword -->
  <testcase classname="test.Login" name="verifyLoginwithInvalidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginwithInvalidCredentials -->
  <testcase classname="test.Login" name="verifyLoginWithoutEnteringCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginWithoutEnteringCredentials -->
</testsuite> <!-- Test(failed) -->
