<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="5" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-22T11:24:26 IST" name="Suite" finished-at="2025-10-22T11:25:12 IST" duration-ms="45339">
    <groups>
      <group name="Regression">
        <method signature="Login.verifyLoginwithInvalidCredentials()[pri:2, instance:test.Login@62150f9e]" name="verifyLoginwithInvalidCredentials" class="test.Login"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="Login.verifyLoginWithValidCredentials()[pri:1, instance:test.Login@62150f9e]" name="verifyLoginWithValidCredentials" class="test.Login"/>
        <method signature="Login.verifyLoginwithInvalidCredentials()[pri:2, instance:test.Login@62150f9e]" name="verifyLoginwithInvalidCredentials" class="test.Login"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2025-10-22T11:24:26 IST" name="Test" finished-at="2025-10-22T11:25:12 IST" duration-ms="45339">
      <class name="test.Login">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.Login@62150f9e]" started-at="2025-10-22T11:24:29 IST" name="setup" finished-at="2025-10-22T11:24:45 IST" duration-ms="16378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithValidCredentials()[pri:1, instance:test.Login@62150f9e]" started-at="2025-10-22T11:24:45 IST" name="verifyLoginWithValidCredentials" finished-at="2025-10-22T11:24:48 IST" duration-ms="2484" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account1] but found [My Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account1] but found [My Account]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.Login.verifyLoginWithValidCredentials(Login.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.Login@62150f9e]" started-at="2025-10-22T11:24:49 IST" name="tearDown" finished-at="2025-10-22T11:24:50 IST" duration-ms="1210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.Login@62150f9e]" started-at="2025-10-22T11:24:50 IST" name="setup" finished-at="2025-10-22T11:25:09 IST" duration-ms="18869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginwithInvalidCredentials()[pri:2, instance:test.Login@62150f9e]" started-at="2025-10-22T11:25:09 IST" name="verifyLoginwithInvalidCredentials" finished-at="2025-10-22T11:25:11 IST" duration-ms="2408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginwithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.Login@62150f9e]" started-at="2025-10-22T11:25:11 IST" name="tearDown" finished-at="2025-10-22T11:25:12 IST" duration-ms="417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
